service: notes-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2

functions:
  createNote:
    handler: handler.createNote # This name is taken from handler.js
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: handler.updateNote # This name is taken from handler.js
    events:
      - http:
          method: put
          path: notes/{id}
  deleteNote:
    handler: handler.deleteNote # This name is taken from handler.js
    events:
      - http:
          method: delete
          path: notes/{id}
  getAllNotes:
    handler: handler.getAllNotes # This name is taken from handler.js
    events:
      - http:
          method: get
          path: notes

# you can add CloudFormation resource templates here
resources:
  Resources:
    notesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH
